import { z } from "zod";
import {
  HTML_ACCEPT,
  IMAGE_ACCEPT,
  OFFICE_ACCEPT,
  PDF_ACCEPT,
  type ToolDefinition,
} from "@/lib/tools/types";

const pageRange = z
  .string()
  .regex(/^\s*$|^\d+(\s*-\s*\d+)?(\s*,\s*\d+(\s*-\s*\d+)?)*$/, {
    message: 'Use page numbers and ranges like "1-3, 5, 8-10"',
  });

export const TOOLS: ToolDefinition[] = [
  {
    id: "merge",
    name: "Merge PDF",
    description: "Combine multiple PDFs into one, in the order you choose.",
    category: "organize",
    accept: PDF_ACCEPT,
    minFiles: 2,
    maxFiles: 20,
    runtime: "client",
    optionsSchema: z.object({}),
    defaultOptions: {},
    optionFields: [],
  },
  {
    id: "split",
    name: "Split PDF",
    description:
      "Split one PDF into several, by page ranges or into single pages.",
    category: "organize",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 1,
    runtime: "client",
    optionsSchema: z.object({ ranges: pageRange }),
    defaultOptions: { ranges: "" },
    optionFields: [
      {
        kind: "text",
        key: "ranges",
        label: "Page ranges (one output file per range; empty = every page)",
        placeholder: "e.g. 1-3, 4-6, 7",
      },
    ],
  },
  {
    id: "extract",
    name: "Extract pages",
    description: "Pull selected pages out of a PDF into a new document.",
    category: "organize",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 1,
    runtime: "client",
    optionsSchema: z.object({ pages: pageRange.min(1) }),
    defaultOptions: { pages: "" },
    optionFields: [
      {
        kind: "text",
        key: "pages",
        label: "Pages to extract",
        placeholder: "e.g. 1, 3-5, 8",
      },
    ],
  },
  {
    id: "rotate",
    name: "Rotate PDF",
    description: "Rotate all pages or selected pages by 90, 180 or 270°.",
    category: "edit",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 10,
    runtime: "client",
    optionsSchema: z.object({
      angle: z.enum(["90", "180", "270"]),
      pages: pageRange,
    }),
    defaultOptions: { angle: "90", pages: "" },
    optionFields: [
      {
        kind: "select",
        key: "angle",
        label: "Rotation",
        choices: [
          { value: "90", label: "90° clockwise" },
          { value: "180", label: "180°" },
          { value: "270", label: "90° counter-clockwise" },
        ],
      },
      {
        kind: "text",
        key: "pages",
        label: "Pages (empty = all)",
        placeholder: "e.g. 2, 4-6",
      },
    ],
  },
  {
    id: "organize",
    name: "Organize PDF",
    description: "Reorder or delete pages visually, with page thumbnails.",
    category: "organize",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 1,
    runtime: "client",
    optionsSchema: z.object({ order: z.array(z.number().int().nonnegative()) }),
    defaultOptions: { order: [] },
    optionFields: [],
    customUI: "organize",
  },
  {
    id: "watermark",
    name: "Watermark",
    description: "Stamp a text watermark over every page.",
    category: "edit",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 10,
    runtime: "client",
    optionsSchema: z.object({
      text: z.string().min(1, "Watermark text is required").max(100),
      fontSize: z.coerce.number().min(8).max(144),
      opacity: z.coerce.number().min(0.05).max(1),
      diagonal: z.boolean(),
    }),
    defaultOptions: {
      text: "CONFIDENTIAL",
      fontSize: 48,
      opacity: 0.25,
      diagonal: true,
    },
    optionFields: [
      { kind: "text", key: "text", label: "Watermark text" },
      {
        kind: "number",
        key: "fontSize",
        label: "Font size",
        min: 8,
        max: 144,
      },
      {
        kind: "number",
        key: "opacity",
        label: "Opacity (0–1)",
        min: 0.05,
        max: 1,
        step: 0.05,
      },
      { kind: "checkbox", key: "diagonal", label: "Diagonal" },
    ],
  },
  {
    id: "page-numbers",
    name: "Page numbers",
    description: "Add page numbers to every page.",
    category: "edit",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 10,
    runtime: "client",
    optionsSchema: z.object({
      position: z.enum(["bottom-center", "bottom-right", "bottom-left"]),
      format: z.enum(["n", "n-of-total"]),
      start: z.coerce.number().int().min(1),
    }),
    defaultOptions: { position: "bottom-center", format: "n", start: 1 },
    optionFields: [
      {
        kind: "select",
        key: "position",
        label: "Position",
        choices: [
          { value: "bottom-center", label: "Bottom center" },
          { value: "bottom-right", label: "Bottom right" },
          { value: "bottom-left", label: "Bottom left" },
        ],
      },
      {
        kind: "select",
        key: "format",
        label: "Format",
        choices: [
          { value: "n", label: "1, 2, 3…" },
          { value: "n-of-total", label: "1 of N" },
        ],
      },
      { kind: "number", key: "start", label: "Start at", min: 1 },
    ],
  },
  {
    id: "images-to-pdf",
    name: "JPG to PDF",
    description: "Turn JPG or PNG images into a single PDF.",
    category: "convert",
    accept: IMAGE_ACCEPT,
    minFiles: 1,
    maxFiles: 50,
    runtime: "client",
    optionsSchema: z.object({
      pageSize: z.enum(["fit", "a4", "letter"]),
      margin: z.coerce.number().min(0).max(100),
    }),
    defaultOptions: { pageSize: "fit", margin: 0 },
    optionFields: [
      {
        kind: "select",
        key: "pageSize",
        label: "Page size",
        choices: [
          { value: "fit", label: "Fit to image" },
          { value: "a4", label: "A4" },
          { value: "letter", label: "Letter" },
        ],
      },
      { kind: "number", key: "margin", label: "Margin (pt)", min: 0, max: 100 },
    ],
  },
  {
    id: "pdf-to-jpg",
    name: "PDF to JPG",
    description: "Render every page of a PDF as a JPG image.",
    category: "convert",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 5,
    runtime: "client",
    optionsSchema: z.object({
      dpi: z.enum(["72", "150", "300"]),
      quality: z.coerce.number().min(0.1).max(1),
    }),
    defaultOptions: { dpi: "150", quality: 0.85 },
    optionFields: [
      {
        kind: "select",
        key: "dpi",
        label: "Resolution",
        choices: [
          { value: "72", label: "72 dpi (screen)" },
          { value: "150", label: "150 dpi (good)" },
          { value: "300", label: "300 dpi (print)" },
        ],
      },
      {
        kind: "number",
        key: "quality",
        label: "JPEG quality (0–1)",
        min: 0.1,
        max: 1,
        step: 0.05,
      },
    ],
  },
  {
    id: "pdf-to-text",
    name: "PDF to Text",
    description: "Extract all the text from a PDF as a plain-text or Markdown file.",
    category: "convert",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 1,
    runtime: "client",
    optionsSchema: z.object({ format: z.enum(["txt", "md"]) }),
    defaultOptions: { format: "txt" },
    optionFields: [
      {
        kind: "select",
        key: "format",
        label: "Output format",
        choices: [
          { value: "txt", label: "Plain text (.txt)" },
          { value: "md", label: "Markdown (.md)" },
        ],
      },
    ],
  },
  {
    id: "pdf-to-excel",
    name: "PDF to Excel",
    description: "Pull tables out of a PDF into an Excel (.xlsx) or CSV spreadsheet.",
    category: "convert",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 1,
    runtime: "client",
    optionsSchema: z.object({ format: z.enum(["xlsx", "csv"]) }),
    defaultOptions: { format: "xlsx" },
    optionFields: [
      {
        kind: "select",
        key: "format",
        label: "Output format",
        choices: [
          { value: "xlsx", label: "Excel workbook (.xlsx)" },
          { value: "csv", label: "CSV (.csv per page)" },
        ],
      },
    ],
  },
  {
    id: "extract-images",
    name: "Extract Images",
    description: "Pull the embedded images out of a PDF and download them as a zip.",
    category: "convert",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 1,
    runtime: "client",
    optionsSchema: z.object({}),
    defaultOptions: {},
    optionFields: [],
  },
  {
    id: "crop",
    name: "Crop PDF",
    description: "Trim the margins of every page by drawing a crop box on the page.",
    category: "organize",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 1,
    runtime: "client",
    optionsSchema: z.object({}),
    defaultOptions: {},
    optionFields: [],
    customUI: "crop",
  },
  {
    id: "edit-metadata",
    name: "Edit Metadata",
    description: "View and change a PDF's title, author, subject and keywords.",
    category: "edit",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 1,
    runtime: "client",
    optionsSchema: z.object({}),
    defaultOptions: {},
    optionFields: [],
    customUI: "metadata",
  },
  {
    id: "replace-image",
    name: "Replace Image",
    description: "Swap an existing image in a PDF for a new one, in the same spot.",
    category: "edit",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 1,
    runtime: "client",
    optionsSchema: z.object({}),
    defaultOptions: {},
    optionFields: [],
    customUI: "replaceimage",
  },
  {
    id: "delete-pages",
    name: "Delete Pages",
    description: "Remove specific pages from a PDF by page number or range.",
    category: "organize",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 1,
    runtime: "client",
    optionsSchema: z.object({ pages: pageRange.min(1) }),
    defaultOptions: { pages: "" },
    optionFields: [
      {
        kind: "text",
        key: "pages",
        label: "Pages to delete",
        placeholder: "e.g. 1, 3, 5-8",
      },
    ],
  },
  {
    id: "n-up",
    name: "N-up (Pages per Sheet)",
    description: "Place multiple pages on one sheet — handouts, thumbnails, booklets.",
    category: "organize",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 1,
    runtime: "client",
    optionsSchema: z.object({ perSheet: z.enum(["2", "4", "6"]) }),
    defaultOptions: { perSheet: "2" },
    optionFields: [
      {
        kind: "select",
        key: "perSheet",
        label: "Pages per sheet",
        choices: [
          { value: "2", label: "2 per sheet" },
          { value: "4", label: "4 per sheet" },
          { value: "6", label: "6 per sheet" },
        ],
      },
    ],
  },
  {
    id: "bates",
    name: "Bates Numbering",
    description: "Stamp sequential Bates numbers (e.g. ABC-000123) on every page.",
    category: "edit",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 1,
    runtime: "client",
    optionsSchema: z.object({
      prefix: z.string(),
      start: z.coerce.number().int().min(0),
      digits: z.coerce.number().int().min(1).max(12),
      position: z.enum(["bottom-right", "bottom-center", "bottom-left"]),
    }),
    defaultOptions: { prefix: "", start: 1, digits: 6, position: "bottom-right" },
    optionFields: [
      { kind: "text", key: "prefix", label: "Prefix (optional)", placeholder: "e.g. ABC-" },
      { kind: "number", key: "start", label: "Start number", min: 0 },
      { kind: "number", key: "digits", label: "Digits (zero-padded)", min: 1, max: 12 },
      {
        kind: "select",
        key: "position",
        label: "Position",
        choices: [
          { value: "bottom-right", label: "Bottom right" },
          { value: "bottom-center", label: "Bottom center" },
          { value: "bottom-left", label: "Bottom left" },
        ],
      },
    ],
  },
  {
    id: "grayscale",
    name: "Grayscale PDF",
    description: "Convert a PDF to black and white — great for cheaper printing.",
    category: "optimize",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 1,
    runtime: "client",
    optionsSchema: z.object({ dpi: z.enum(["72", "150", "300"]) }),
    defaultOptions: { dpi: "150" },
    optionFields: [
      {
        kind: "select",
        key: "dpi",
        label: "Resolution",
        choices: [
          { value: "72", label: "72 dpi (screen)" },
          { value: "150", label: "150 dpi (good)" },
          { value: "300", label: "300 dpi (print)" },
        ],
      },
    ],
  },
  {
    id: "pdf-to-png",
    name: "PDF to PNG",
    description: "Render every page of a PDF as a lossless PNG image.",
    category: "convert",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 5,
    runtime: "client",
    optionsSchema: z.object({ dpi: z.enum(["72", "150", "300"]) }),
    defaultOptions: { dpi: "150" },
    optionFields: [
      {
        kind: "select",
        key: "dpi",
        label: "Resolution",
        choices: [
          { value: "72", label: "72 dpi (screen)" },
          { value: "150", label: "150 dpi (good)" },
          { value: "300", label: "300 dpi (print)" },
        ],
      },
    ],
  },
  {
    id: "sanitize",
    name: "Sanitize PDF",
    description: "Strip metadata and hidden document info before sharing.",
    category: "security",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 1,
    runtime: "client",
    optionsSchema: z.object({}),
    defaultOptions: {},
    optionFields: [],
  },
  {
    id: "flatten-pdf",
    name: "Flatten PDF",
    description: "Bake interactive form fields into the page so they can't be edited.",
    category: "edit",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 1,
    runtime: "client",
    optionsSchema: z.object({}),
    defaultOptions: {},
    optionFields: [],
  },
  {
    id: "header-footer",
    name: "Header & Footer",
    description: "Add running header/footer text with page-number and date placeholders.",
    category: "edit",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 1,
    runtime: "client",
    optionsSchema: z.object({
      header: z.string(),
      footer: z.string(),
      align: z.enum(["left", "center", "right"]),
    }),
    defaultOptions: { header: "", footer: "", align: "center" },
    optionFields: [
      { kind: "text", key: "header", label: "Header text", placeholder: "e.g. Confidential — {date}" },
      { kind: "text", key: "footer", label: "Footer text", placeholder: "e.g. Page {page} of {pages}" },
      {
        kind: "select",
        key: "align",
        label: "Alignment",
        choices: [
          { value: "left", label: "Left" },
          { value: "center", label: "Center" },
          { value: "right", label: "Right" },
        ],
      },
    ],
  },
  {
    id: "resize",
    name: "Resize PDF",
    description: "Scale every page to a standard paper size (A4 or US Letter).",
    category: "organize",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 1,
    runtime: "client",
    optionsSchema: z.object({ size: z.enum(["a4", "letter"]) }),
    defaultOptions: { size: "a4" },
    optionFields: [
      {
        kind: "select",
        key: "size",
        label: "Target size",
        choices: [
          { value: "a4", label: "A4 (210×297 mm)" },
          { value: "letter", label: "US Letter (8.5×11 in)" },
        ],
      },
    ],
  },
  {
    id: "batch",
    name: "Batch Process",
    description: "Apply one tool to many PDFs at once and download them as a zip.",
    category: "organize",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 100,
    runtime: "client",
    optionsSchema: z.object({}),
    defaultOptions: {},
    optionFields: [],
    customUI: "batch",
  },
  {
    id: "pipeline",
    name: "PDF Pipeline",
    description: "Chain several PDF tools into one workflow — run them in sequence.",
    category: "organize",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 1,
    runtime: "client",
    optionsSchema: z.object({}),
    defaultOptions: {},
    optionFields: [],
    customUI: "pipeline",
  },
  {
    id: "annotate",
    name: "Annotate PDF",
    description: "Add sticky-note comments and highlights as real, editable PDF annotations.",
    category: "edit",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 1,
    runtime: "client",
    optionsSchema: z.object({}),
    defaultOptions: {},
    optionFields: [],
    customUI: "annotate",
  },
  {
    id: "visual-compare",
    name: "Visual Compare",
    description: "Spot pixel-level visual differences between two PDF versions.",
    category: "edit",
    accept: PDF_ACCEPT,
    minFiles: 2,
    maxFiles: 2,
    runtime: "client",
    optionsSchema: z.object({}),
    defaultOptions: {},
    optionFields: [],
    customUI: "visualcompare",
  },
  {
    id: "linearize",
    name: "Optimize for Web",
    description: "Linearize a PDF for fast progressive loading (Fast Web View).",
    category: "optimize",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 1,
    runtime: "server",
    optionsSchema: z.object({}),
    defaultOptions: {},
    optionFields: [],
  },
  {
    id: "edit",
    name: "Edit PDF",
    description:
      "Edit existing text in place, or add text, shapes, highlights and images.",
    category: "edit",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 1,
    runtime: "client",
    optionsSchema: z.object({}),
    defaultOptions: {},
    optionFields: [],
    customUI: "edit",
  },
  {
    id: "sign",
    name: "Sign PDF",
    description: "Draw, type or upload your signature and place it on the document.",
    category: "edit",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 1,
    runtime: "client",
    optionsSchema: z.object({}),
    defaultOptions: {},
    optionFields: [],
    customUI: "sign",
  },
  {
    id: "fill-form",
    name: "Fill PDF Form",
    description:
      "Fill in interactive PDF form fields, then download — optionally flattened.",
    category: "edit",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 1,
    runtime: "client",
    optionsSchema: z.object({}),
    defaultOptions: {},
    optionFields: [],
    customUI: "fillform",
  },
  {
    id: "compare",
    name: "Compare PDF",
    description: "Find text differences between two versions of a document.",
    category: "edit",
    accept: PDF_ACCEPT,
    minFiles: 2,
    maxFiles: 2,
    runtime: "client",
    optionsSchema: z.object({}),
    defaultOptions: {},
    optionFields: [],
    customUI: "compare",
  },
  {
    id: "redact",
    name: "Redact PDF",
    description: "Black out sensitive content — permanently and unrecoverably.",
    category: "security",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 1,
    runtime: "client",
    optionsSchema: z.object({}),
    defaultOptions: {},
    optionFields: [],
    customUI: "redact",
  },
  // ——— Server tools (processed on the server, auto-deleted after 1 hour) ———
  {
    id: "compress",
    name: "Compress PDF",
    description: "Shrink a PDF’s file size while keeping the best quality possible.",
    category: "optimize",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 5,
    runtime: "server",
    optionsSchema: z.object({ level: z.enum(["extreme", "recommended", "light"]) }),
    defaultOptions: { level: "recommended" },
    optionFields: [
      {
        kind: "select",
        key: "level",
        label: "Compression level",
        choices: [
          { value: "extreme", label: "Extreme (smallest, lower quality)" },
          { value: "recommended", label: "Recommended (good quality)" },
          { value: "light", label: "Light (highest quality)" },
        ],
      },
    ],
  },
  {
    id: "office-to-pdf",
    name: "Office to PDF",
    description: "Convert Word, Excel or PowerPoint documents to PDF.",
    category: "convert",
    accept: OFFICE_ACCEPT,
    minFiles: 1,
    maxFiles: 10,
    runtime: "server",
    optionsSchema: z.object({}),
    defaultOptions: {},
    optionFields: [],
  },
  {
    id: "pdf-to-word",
    name: "PDF to Word",
    description:
      "Convert a PDF to an editable Word document (best effort — complex layouts may shift).",
    category: "convert",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 5,
    runtime: "server",
    optionsSchema: z.object({}),
    defaultOptions: {},
    optionFields: [],
  },
  {
    id: "pdf-to-powerpoint",
    name: "PDF to PowerPoint",
    description:
      "Convert a PDF into PowerPoint slides (best effort — complex layouts may shift).",
    category: "convert",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 5,
    runtime: "server",
    optionsSchema: z.object({}),
    defaultOptions: {},
    optionFields: [],
  },
  {
    id: "html-to-pdf",
    name: "HTML to PDF",
    description: "Render an HTML file to PDF with a real browser engine.",
    category: "convert",
    accept: HTML_ACCEPT,
    minFiles: 1,
    maxFiles: 1,
    runtime: "server",
    optionsSchema: z.object({}),
    defaultOptions: {},
    optionFields: [],
  },
  {
    id: "protect",
    name: "Protect PDF",
    description: "Encrypt a PDF with a password (AES-256).",
    category: "security",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 5,
    runtime: "server",
    optionsSchema: z.object({
      password: z.string().min(4, "Password must be at least 4 characters").max(64),
    }),
    defaultOptions: { password: "" },
    optionFields: [{ kind: "password", key: "password", label: "Password" }],
  },
  {
    id: "unlock",
    name: "Unlock PDF",
    description: "Remove a password from a PDF you own the password for.",
    category: "security",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 5,
    runtime: "server",
    optionsSchema: z.object({
      password: z.string().min(1, "Enter the PDF’s password").max(64),
    }),
    defaultOptions: { password: "" },
    optionFields: [{ kind: "password", key: "password", label: "Current password" }],
  },
  {
    id: "ocr",
    name: "OCR PDF",
    description: "Make scanned PDFs searchable and selectable with OCR.",
    category: "optimize",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 5,
    runtime: "server",
    optionsSchema: z.object({ language: z.enum(["eng", "deu", "fra", "spa", "hin"]) }),
    defaultOptions: { language: "eng" },
    optionFields: [
      {
        kind: "select",
        key: "language",
        label: "Document language",
        choices: [
          { value: "eng", label: "English" },
          { value: "deu", label: "German" },
          { value: "fra", label: "French" },
          { value: "spa", label: "Spanish" },
          { value: "hin", label: "Hindi" },
        ],
      },
    ],
  },
  {
    id: "repair",
    name: "Repair PDF",
    description: "Try to recover a damaged PDF by rebuilding its structure.",
    category: "optimize",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 5,
    runtime: "server",
    optionsSchema: z.object({}),
    defaultOptions: {},
    optionFields: [],
  },
  {
    id: "pdfa",
    name: "PDF to PDF/A",
    description: "Convert a PDF to PDF/A for long-term archiving.",
    category: "convert",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 5,
    runtime: "server",
    optionsSchema: z.object({}),
    defaultOptions: {},
    optionFields: [],
  },
];

export function getTool(id: string): ToolDefinition | undefined {
  return TOOLS.find((t) => t.id === id);
}
