import { z } from "zod";
import {
  HTML_ACCEPT,
  IMAGE_ACCEPT,
  OFFICE_ACCEPT,
  PDF_ACCEPT,
  type ToolDefinition,
} from "@/lib/tools/types";

const pageRange = z
  .string()
  .regex(/^\s*$|^\d+(\s*-\s*\d+)?(\s*,\s*\d+(\s*-\s*\d+)?)*$/, {
    message: 'Use page numbers and ranges like "1-3, 5, 8-10"',
  });

export const TOOLS: ToolDefinition[] = [
  {
    id: "merge",
    name: "Merge PDF",
    description: "Combine multiple PDFs into one, in the order you choose.",
    category: "organize",
    accept: PDF_ACCEPT,
    minFiles: 2,
    maxFiles: 20,
    runtime: "client",
    optionsSchema: z.object({}),
    defaultOptions: {},
    optionFields: [],
  },
  {
    id: "split",
    name: "Split PDF",
    description:
      "Split one PDF into several, by page ranges or into single pages.",
    category: "organize",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 1,
    runtime: "client",
    optionsSchema: z.object({ ranges: pageRange }),
    defaultOptions: { ranges: "" },
    optionFields: [
      {
        kind: "text",
        key: "ranges",
        label: "Page ranges (one output file per range; empty = every page)",
        placeholder: "e.g. 1-3, 4-6, 7",
      },
    ],
  },
  {
    id: "extract",
    name: "Extract pages",
    description: "Pull selected pages out of a PDF into a new document.",
    category: "organize",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 1,
    runtime: "client",
    optionsSchema: z.object({ pages: pageRange.min(1) }),
    defaultOptions: { pages: "" },
    optionFields: [
      {
        kind: "text",
        key: "pages",
        label: "Pages to extract",
        placeholder: "e.g. 1, 3-5, 8",
      },
    ],
  },
  {
    id: "rotate",
    name: "Rotate PDF",
    description: "Rotate all pages or selected pages by 90, 180 or 270°.",
    category: "edit",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 10,
    runtime: "client",
    optionsSchema: z.object({
      angle: z.enum(["90", "180", "270"]),
      pages: pageRange,
    }),
    defaultOptions: { angle: "90", pages: "" },
    optionFields: [
      {
        kind: "select",
        key: "angle",
        label: "Rotation",
        choices: [
          { value: "90", label: "90° clockwise" },
          { value: "180", label: "180°" },
          { value: "270", label: "90° counter-clockwise" },
        ],
      },
      {
        kind: "text",
        key: "pages",
        label: "Pages (empty = all)",
        placeholder: "e.g. 2, 4-6",
      },
    ],
  },
  {
    id: "organize",
    name: "Organize PDF",
    description: "Reorder or delete pages visually, with page thumbnails.",
    category: "organize",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 1,
    runtime: "client",
    optionsSchema: z.object({ order: z.array(z.number().int().nonnegative()) }),
    defaultOptions: { order: [] },
    optionFields: [],
    customUI: "organize",
  },
  {
    id: "watermark",
    name: "Watermark",
    description: "Stamp a text watermark over every page.",
    category: "edit",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 10,
    runtime: "client",
    optionsSchema: z.object({
      text: z.string().min(1, "Watermark text is required").max(100),
      fontSize: z.coerce.number().min(8).max(144),
      opacity: z.coerce.number().min(0.05).max(1),
      diagonal: z.boolean(),
    }),
    defaultOptions: {
      text: "CONFIDENTIAL",
      fontSize: 48,
      opacity: 0.25,
      diagonal: true,
    },
    optionFields: [
      { kind: "text", key: "text", label: "Watermark text" },
      {
        kind: "number",
        key: "fontSize",
        label: "Font size",
        min: 8,
        max: 144,
      },
      {
        kind: "number",
        key: "opacity",
        label: "Opacity (0–1)",
        min: 0.05,
        max: 1,
        step: 0.05,
      },
      { kind: "checkbox", key: "diagonal", label: "Diagonal" },
    ],
  },
  {
    id: "page-numbers",
    name: "Page numbers",
    description: "Add page numbers to every page.",
    category: "edit",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 10,
    runtime: "client",
    optionsSchema: z.object({
      position: z.enum(["bottom-center", "bottom-right", "bottom-left"]),
      format: z.enum(["n", "n-of-total"]),
      start: z.coerce.number().int().min(1),
    }),
    defaultOptions: { position: "bottom-center", format: "n", start: 1 },
    optionFields: [
      {
        kind: "select",
        key: "position",
        label: "Position",
        choices: [
          { value: "bottom-center", label: "Bottom center" },
          { value: "bottom-right", label: "Bottom right" },
          { value: "bottom-left", label: "Bottom left" },
        ],
      },
      {
        kind: "select",
        key: "format",
        label: "Format",
        choices: [
          { value: "n", label: "1, 2, 3…" },
          { value: "n-of-total", label: "1 of N" },
        ],
      },
      { kind: "number", key: "start", label: "Start at", min: 1 },
    ],
  },
  {
    id: "images-to-pdf",
    name: "JPG to PDF",
    description: "Turn JPG or PNG images into a single PDF.",
    category: "convert",
    accept: IMAGE_ACCEPT,
    minFiles: 1,
    maxFiles: 50,
    runtime: "client",
    optionsSchema: z.object({
      pageSize: z.enum(["fit", "a4", "letter"]),
      margin: z.coerce.number().min(0).max(100),
    }),
    defaultOptions: { pageSize: "fit", margin: 0 },
    optionFields: [
      {
        kind: "select",
        key: "pageSize",
        label: "Page size",
        choices: [
          { value: "fit", label: "Fit to image" },
          { value: "a4", label: "A4" },
          { value: "letter", label: "Letter" },
        ],
      },
      { kind: "number", key: "margin", label: "Margin (pt)", min: 0, max: 100 },
    ],
  },
  {
    id: "pdf-to-jpg",
    name: "PDF to JPG",
    description: "Render every page of a PDF as a JPG image.",
    category: "convert",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 5,
    runtime: "client",
    optionsSchema: z.object({
      dpi: z.enum(["72", "150", "300"]),
      quality: z.coerce.number().min(0.1).max(1),
    }),
    defaultOptions: { dpi: "150", quality: 0.85 },
    optionFields: [
      {
        kind: "select",
        key: "dpi",
        label: "Resolution",
        choices: [
          { value: "72", label: "72 dpi (screen)" },
          { value: "150", label: "150 dpi (good)" },
          { value: "300", label: "300 dpi (print)" },
        ],
      },
      {
        kind: "number",
        key: "quality",
        label: "JPEG quality (0–1)",
        min: 0.1,
        max: 1,
        step: 0.05,
      },
    ],
  },
  {
    id: "edit",
    name: "Edit PDF",
    description:
      "Edit existing text in place, or add text, shapes, highlights and images.",
    category: "edit",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 1,
    runtime: "client",
    optionsSchema: z.object({}),
    defaultOptions: {},
    optionFields: [],
    customUI: "edit",
  },
  {
    id: "sign",
    name: "Sign PDF",
    description: "Draw, type or upload your signature and place it on the document.",
    category: "edit",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 1,
    runtime: "client",
    optionsSchema: z.object({}),
    defaultOptions: {},
    optionFields: [],
    customUI: "sign",
  },
  {
    id: "compare",
    name: "Compare PDF",
    description: "Find text differences between two versions of a document.",
    category: "edit",
    accept: PDF_ACCEPT,
    minFiles: 2,
    maxFiles: 2,
    runtime: "client",
    optionsSchema: z.object({}),
    defaultOptions: {},
    optionFields: [],
    customUI: "compare",
  },
  {
    id: "redact",
    name: "Redact PDF",
    description: "Black out sensitive content — permanently and unrecoverably.",
    category: "security",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 1,
    runtime: "client",
    optionsSchema: z.object({}),
    defaultOptions: {},
    optionFields: [],
    customUI: "redact",
  },
  // ——— Server tools (processed on the server, auto-deleted after 1 hour) ———
  {
    id: "compress",
    name: "Compress PDF",
    description: "Shrink a PDF’s file size while keeping the best quality possible.",
    category: "optimize",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 5,
    runtime: "server",
    optionsSchema: z.object({ level: z.enum(["extreme", "recommended", "light"]) }),
    defaultOptions: { level: "recommended" },
    optionFields: [
      {
        kind: "select",
        key: "level",
        label: "Compression level",
        choices: [
          { value: "extreme", label: "Extreme (smallest, lower quality)" },
          { value: "recommended", label: "Recommended (good quality)" },
          { value: "light", label: "Light (highest quality)" },
        ],
      },
    ],
  },
  {
    id: "office-to-pdf",
    name: "Office to PDF",
    description: "Convert Word, Excel or PowerPoint documents to PDF.",
    category: "convert",
    accept: OFFICE_ACCEPT,
    minFiles: 1,
    maxFiles: 10,
    runtime: "server",
    optionsSchema: z.object({}),
    defaultOptions: {},
    optionFields: [],
  },
  {
    id: "pdf-to-word",
    name: "PDF to Word",
    description:
      "Convert a PDF to an editable Word document (best effort — complex layouts may shift).",
    category: "convert",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 5,
    runtime: "server",
    optionsSchema: z.object({}),
    defaultOptions: {},
    optionFields: [],
  },
  {
    id: "pdf-to-powerpoint",
    name: "PDF to PowerPoint",
    description:
      "Convert a PDF into PowerPoint slides (best effort — complex layouts may shift).",
    category: "convert",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 5,
    runtime: "server",
    optionsSchema: z.object({}),
    defaultOptions: {},
    optionFields: [],
  },
  {
    id: "html-to-pdf",
    name: "HTML to PDF",
    description: "Render an HTML file to PDF with a real browser engine.",
    category: "convert",
    accept: HTML_ACCEPT,
    minFiles: 1,
    maxFiles: 1,
    runtime: "server",
    optionsSchema: z.object({}),
    defaultOptions: {},
    optionFields: [],
  },
  {
    id: "protect",
    name: "Protect PDF",
    description: "Encrypt a PDF with a password (AES-256).",
    category: "security",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 5,
    runtime: "server",
    optionsSchema: z.object({
      password: z.string().min(4, "Password must be at least 4 characters").max(64),
    }),
    defaultOptions: { password: "" },
    optionFields: [{ kind: "password", key: "password", label: "Password" }],
  },
  {
    id: "unlock",
    name: "Unlock PDF",
    description: "Remove a password from a PDF you own the password for.",
    category: "security",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 5,
    runtime: "server",
    optionsSchema: z.object({
      password: z.string().min(1, "Enter the PDF’s password").max(64),
    }),
    defaultOptions: { password: "" },
    optionFields: [{ kind: "password", key: "password", label: "Current password" }],
  },
  {
    id: "ocr",
    name: "OCR PDF",
    description: "Make scanned PDFs searchable and selectable with OCR.",
    category: "optimize",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 5,
    runtime: "server",
    optionsSchema: z.object({ language: z.enum(["eng", "deu", "fra", "spa", "hin"]) }),
    defaultOptions: { language: "eng" },
    optionFields: [
      {
        kind: "select",
        key: "language",
        label: "Document language",
        choices: [
          { value: "eng", label: "English" },
          { value: "deu", label: "German" },
          { value: "fra", label: "French" },
          { value: "spa", label: "Spanish" },
          { value: "hin", label: "Hindi" },
        ],
      },
    ],
  },
  {
    id: "repair",
    name: "Repair PDF",
    description: "Try to recover a damaged PDF by rebuilding its structure.",
    category: "optimize",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 5,
    runtime: "server",
    optionsSchema: z.object({}),
    defaultOptions: {},
    optionFields: [],
  },
  {
    id: "pdfa",
    name: "PDF to PDF/A",
    description: "Convert a PDF to PDF/A for long-term archiving.",
    category: "convert",
    accept: PDF_ACCEPT,
    minFiles: 1,
    maxFiles: 5,
    runtime: "server",
    optionsSchema: z.object({}),
    defaultOptions: {},
    optionFields: [],
  },
];

export function getTool(id: string): ToolDefinition | undefined {
  return TOOLS.find((t) => t.id === id);
}
